# -*- coding: utf-8 -*-
"""Netfilx-review.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XCp_d_cUwWpqay3jBx9YxnIbyP6AELDr
"""

# importing libraries -
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# reading the data file

# Make sure to upload 'netflix.csv' to your Colab environment first (e.g., to /content/netflix.csv)
df=pd.read_csv('/content/netflix.csv')
df.head(5)

df.sample(10)

df.shape

df.info()

df.describe(include='all').T

# checking null values -
df.isna().sum()

df['type'].value_counts(normalize=True) * 100

constraint1=df['director'].apply(lambda x: str(x).split(', ')).tolist()
constraint1

df_new1=pd.DataFrame(constraint1, index=df['title'])
df_new1=df_new1.stack()
df_new1=pd.DataFrame(df_new1.reset_index())
df_new1.rename(columns={0:'Director'}, inplace=True)
df_new1.drop(['level_1'], axis=1, inplace=True)
df_new1.head(50)

# unnesting the cast column -
constraint2=df['cast'].apply(lambda x: str(x).split(', ')).tolist()
df_new2=pd.DataFrame(constraint2, index=df['title'])
df_new2=df_new2.stack()
df_new2=pd.DataFrame(df_new2.reset_index())
df_new2.rename(columns={0:'Cast'}, inplace=True)
df_new2.drop(['level_1'], axis=1, inplace=True)
df_new2.head(50)

# unnesting the listed_in column -
constraint3=df['listed_in'].apply(lambda x: str(x).split(', ')).tolist()
df_new3=pd.DataFrame(constraint3, index=df['title'])
df_new3=df_new3.stack()
df_new3=pd.DataFrame(df_new3.reset_index())
df_new3.rename(columns={0:'Genre'}, inplace=True)
df_new3.drop(['level_1'], axis=1, inplace=True)
df_new3.head()

df_new3.groupby(['Genre']).agg({"title":"nunique"}).reset_index().sort_values(by=['title'],
                                                                                 ascending=False)

# unnesting the country column -
constraint4=df['country'].apply(lambda x: str(x).split(', ')).tolist()
df_new4=pd.DataFrame(constraint4, index=df['title'])
df_new4=df_new4.stack()
df_new4=pd.DataFrame(df_new4.reset_index())
df_new4.rename(columns={0:'Country'}, inplace=True)
df_new4.drop(['level_1'], axis=1, inplace=True)
df_new4.head()

df_new4.groupby(['Country']).agg({"title":"nunique"}).reset_index().sort_values(by=['title'],
                                                                                 ascending=False)

# merging the unnested director data with unnested cast data
df_new5=df_new2.merge(df_new1, on=['title'], how='inner')
# merging the above merged data with unnested genre data
df_new6=df_new5.merge(df_new3, on=['title'], how='inner')
# merging the above merged data with unnested country data
df_new=df_new6.merge(df_new4, on=['title'], how='inner')

# replacing nan values of director and cast by Unknown
df_new['Cast'].replace(['nan'], ['Unknown'], inplace=True)
df_new['Director'].replace(['nan'], ['Unknown'], inplace=True)
df_new['Country'].replace(['nan'], [np.nan], inplace=True)

df_new.head()

