# -*- coding: utf-8 -*-
"""OLA - Ensemble Learning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cn8Dc_t1jyKAWWcP6UbBpwdDwuvTVBGJ
"""

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os

import random
#For dealing with tables
import pandas as pd
#For dealing with linear algebra
import numpy as np
#For data visualization and plotting graphs
import matplotlib.pyplot as plt
import seaborn as sns
#For minmaxscaler
from sklearn.preprocessing import MinMaxScaler
#For shapiro test
from scipy.stats import shapiro
#For train-test split
from sklearn.model_selection import train_test_split,GridSearchCV
#For RandomForest
from sklearn.ensemble import RandomForestClassifier
#Accuracy score, confusion matrix, classification report, ROC curve, AUC
from sklearn.metrics import f1_score
#To ignore warnings
import warnings
warnings.filterwarnings("ignore")
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report,confusion_matrix

from google.colab import drive
drive.mount('/content/drive')

_data = pd.read_csv('https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/002/492/original/ola_driver_scaler.csv')
_data

_data=_data.drop(columns='Unnamed: 0')

_data

_data.info()

##Converting 'MMM-YY' feature to datetime type
_data['MMM-YY'] = pd.to_datetime(_data['MMM-YY'])

##Converting 'Dateofjoining' feature to datetime type
_data['Dateofjoining'] = pd.to_datetime(_data['Dateofjoining'])

##Converting 'LastWorkingDate' feature to datetime type
_data['LastWorkingDate'] = pd.to_datetime(_data['LastWorkingDate'])

_data

_data.info()

## Step:Imputation of missing data

_data.isnull().sum()/len(_data)*100

_data['Gender'].value_counts()

_data['Education_Level'].value_counts()

_data['Age'].value_counts()

_data['LastWorkingDate'].value_counts()

"""# KNN Imputation"""

_data_nums=_data.select_dtypes(np.number)

_data_nums

_data_nums.isnull().sum()

_data_nums.drop(columns='Driver_ID',inplace=True)
columns=_data_nums.columns

from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=5, weights='uniform', metric='nan_euclidean',)
imputer.fit(_data_nums)
# transform the dataset
_data_new = imputer.transform(_data_nums)

_data_new=pd.DataFrame(_data_new)

_data_new

_data_new.columns=columns

_data_new.isnull().sum()

"""### Getting the remaining columns back

### Checking if the concat is correct or not

# Aggregation at Driver Level
"""

import pandas as pd

# Create a temporary DataFrame for aggregation that includes Driver_ID and City
# along with the imputed numerical features. Ensure that concatenation aligns rows correctly.
_data_for_aggregation = pd.concat([_data[['Driver_ID', 'City']], _data_new], axis=1)

# Initialize df1 with unique Driver_IDs as the index.
df1 = pd.DataFrame(index=_data_for_aggregation['Driver_ID'].unique())

# Aggregate the features from _data_for_aggregation
df1['Age'] = _data_for_aggregation.groupby('Driver_ID')['Age'].max()
df1['Gender'] = _data_for_aggregation.groupby('Driver_ID').agg({'Gender':'last'})['Gender']
df1['City'] = _data_for_aggregation.groupby('Driver_ID').agg({'City':'last'})['City']
df1['Education'] = _data_for_aggregation.groupby('Driver_ID').agg({'Education_Level':'last'})['Education_Level']
df1['Income'] = _data_for_aggregation.groupby('Driver_ID').agg({'Income':'last'})['Income']
df1['Joining_Designation'] = _data_for_aggregation.groupby('Driver_ID').agg({'Joining Designation':'last'})['Joining Designation']
df1['Grade'] = _data_for_aggregation.groupby('Driver_ID').agg({'Grade':'last'})['Grade']
df1['Total_Business_Value'] = _data_for_aggregation.groupby('Driver_ID')['Total Business Value'].sum()
df1['Last_Quarterly_Rating'] = _data_for_aggregation.groupby('Driver_ID').agg({'Quarterly Rating':'last'})['Quarterly Rating']

# Convert the Series results of groupby into lists to match the original code's intent
for col in df1.columns:
    df1[col] = list(df1[col])

"""XGBOOST + SHAP"""

#1. Install Required Libraries
# ==============================
!pip install xgboost shap

# 2. Import Libraries
# ==============================
import pandas as pd
import numpy as np
from xgboost import XGBClassifier
import shap

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, f1_score

# 3. Prepare Data
# ==============================

df_model = df1.copy()

# Convert categorical to numeric
df_model = pd.get_dummies(df_model, drop_first=True)

# Convert boolean columns (from get_dummies) to int (0 or 1)
for col in df_model.columns:
    if df_model[col].dtype == 'bool':
        df_model[col] = df_model[col].astype(int)

# Target variable (IMPORTANT)
# Create attrition label
df_model['Attrition'] = np.where(df_model['Total_Business_Value'] <= 0, 1, 0)

X = df_model.drop('Attrition', axis=1)
y = df_model['Attrition']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 4. XGBoost Model
# ==============================

model = XGBClassifier(
    n_estimators=200,
    max_depth=6,
    learning_rate=0.1,
    subsample=0.8,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Evaluation
print("F1 Score:", f1_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# SHAP Explainability
# ==============================

explainer = shap.Explainer(model, X_train)
shap_values = explainer(X_test)

# Summary plot
shap.plots.beeswarm(shap_values)

# Feature importance
shap.plots.bar(shap_values)

"""✅ SMOTE + XGBOOST"""

# ==============================
# 1. Install Required Libraries
# ==============================
!pip install xgboost imbalanced-learn shap

# ==============================
# 2. Import Libraries
# ==============================
import pandas as pd
import numpy as np

from xgboost import XGBClassifier
from imblearn.over_sampling import SMOTE

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix, f1_score, roc_auc_score

# ==============================
# 3. Prepare Data
# ==============================
df_model = df1.copy()

# Convert categorical variables
df_model = pd.get_dummies(df_model, drop_first=True)

# Create target variable (Attrition)
df_model['Attrition'] = np.where(df_model['Total_Business_Value'] <= 0, 1, 0)

X = df_model.drop('Attrition', axis=1)
y = df_model['Attrition']

# Train-test split (IMPORTANT: before SMOTE)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# ==============================
# 4. Apply SMOTE (ONLY on train)
# ==============================
smote = SMOTE(random_state=42)
X_train_sm, y_train_sm = smote.fit_resample(X_train, y_train)

print("Before SMOTE:", np.bincount(y_train))
print("After SMOTE:", np.bincount(y_train_sm))

# ==============================
# 5. Train XGBoost Model
# ==============================
model = XGBClassifier(
    n_estimators=300,
    max_depth=6,
    learning_rate=0.05,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    n_jobs=-1
)

model.fit(X_train_sm, y_train_sm)

# ==============================
# 6. Predictions & Evaluation
# ==============================
y_pred = model.predict(X_test)
y_prob = model.predict_proba(X_test)[:, 1]

print("\nF1 Score:", f1_score(y_test, y_pred))
print("ROC-AUC:", roc_auc_score(y_test, y_prob))

print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))