# -*- coding: utf-8 -*-
"""Untitled30.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aPMLNxr_IVzTFOY3VkkPegGsJ_GSmB2P
"""

!pip install faiss-cpu

import os, sys, json, re, csv, pickle, time
import numpy as np
import faiss
from pathlib import Path
from datetime import datetime
from sentence_transformers import SentenceTransformer

# Assuming the enterprise_knowledge_base.csv is uploaded to /content/data/
BASE = Path("/content/Data/")
DATA_PATH  = BASE / "enterprise_knowledge_base.csv"
INDEX_DIR  = Path("/content/indexes") # Adjusted for Colab environment
OUTPUT_DIR = Path("/content/output") # Adjusted for Colab environment
INDEX_DIR.mkdir(exist_ok=True);
OUTPUT_DIR.mkdir(exist_ok=True)

import os
from google.colab import files

# Ensure the directory exists
if not os.path.exists('/content/Data'):
    os.makedirs('/content/Data')

print("Please select the 'enterprise_knowledge_base.csv' file to upload:")
uploaded = files.upload()

for filename in uploaded.keys():
    with open(os.path.join('/content/Data', filename), 'wb') as f:
        f.write(uploaded[filename])
    print(f"File '{filename}' uploaded to '/content/Data/'")

print("\n" + "█"*65)
print("  RAG PIPELINE — FULL END-TO-END RUN")
print("  No API Keys | No Payments | 100% Local")
print("█"*65)

t_total = time.time()

# ── STAGE 1: INDEXING ─────────────────────────────────────────────
print("\n[STAGE 1/5] DOCUMENT INDEXING")
print("—"*45)
import pandas as pd

print("Loading embedding model (all-MiniLM-L6-v2)...")
model = SentenceTransformer("all-MiniLM-L6-v2")

df = pd.read_csv(DATA_PATH)
print(f"Loaded {len(df)} documents")

def chunk_text(text, size=80, overlap=15):
    words = text.split()
    out = []
    i = 0
    while i < len(words):
        out.append(" ".join(words[i:i+size]))
        if i+size >= len(words): break
        i += size - overlap
    return out

all_chunks, all_metadata = [], []
for _, row in df.iterrows():
    text   = f"{row['title']}: {row['content']}"
    parts  = chunk_text(text)
    for j, p in enumerate(parts):
        all_chunks.append(p)
        all_metadata.append({
            "doc_id":     row["doc_id"],
            "title":      row["title"],
            "department": row["department"],
            "category":   row["category"],
            "author":     row["author"],
            "year":       str(row["year"]),
            "chunk_idx":  j,
        })

print(f"Created {len(all_chunks)} chunks")
embeddings = model.encode(all_chunks, batch_size=32, show_progress_bar=True,
                           normalize_embeddings=True)
dim   = embeddings.shape[1]
index = faiss.IndexFlatIP(dim)
index.add(embeddings.astype(np.float32))

faiss.write_index(index, str(INDEX_DIR/"knowledge_base.faiss"))
with open(INDEX_DIR/"chunks.pkl",   "wb") as f: pickle.dump(all_chunks,   f)
with open(INDEX_DIR/"metadata.pkl", "wb") as f: pickle.dump(all_metadata, f)
print(f"✓ Stage 1 complete — {index.ntotal} vectors indexed")

"""### Helper Function for Similarity Search

The following function `similarity_search` will take a query string, encode it using the same `SentenceTransformer` model used for indexing, and then perform a similarity search against the FAISS index. It retrieves the top `k` most similar chunks and combines them with their corresponding metadata.
"""

def similarity_search(query: str, index: faiss.Index, model: SentenceTransformer, chunks: list, metadata: list, k: int = 5) -> list:
    """
    Performs a similarity search on the FAISS index given a query.

    Args:
        query (str): The search query.
        index (faiss.Index): The FAISS index.
        model (SentenceTransformer): The sentence transformer model.
        chunks (list): List of all text chunks.
        metadata (list): List of metadata for all chunks.
        k (int): The number of top results to return.

    Returns:
        list: A list of dictionaries, each containing 'text', 'score', and 'metadata' for the top k results.
    """
    query_embedding = model.encode([query], normalize_embeddings=True).astype(np.float32)
    distances, indices = index.search(query_embedding, k)

    results = []
    for i in range(k):
        idx = indices[0][i]
        score = distances[0][i]
        results.append({
            "text": chunks[idx],
            "score": float(score),
            "metadata": metadata[idx]
        })
    return results

"""### Test the Similarity Search Function

Let's test the `similarity_search` function with a sample query to retrieve the most relevant chunks from the indexed knowledge base.
"""

# Sample Query
query = "What are the benefits for employees?"

# Perform similarity search
search_results = similarity_search(query, index, model, all_chunks, all_metadata, k=3)

# Display the results
print(f"Top 3 results for query: '{query}'")
print("—"*50)
for i, result in enumerate(search_results):
    print(f"Result {i+1} (Score: {result['score']:.4f}):\n{result['text']}\nMetadata: {result['metadata']}\n")
print("—"*50)

# ── STAGE 2: RETRIEVAL DEMO ───────────────────────────────────────
print("\n[STAGE 2/5] RETRIEVAL DEMONSTRATION")
print("—"*45)

def retrieve(query, k=4, dept=None):
    qv = model.encode([query], normalize_embeddings=True)
    scores, ids = index.search(qv.astype(np.float32), k*3)
    out = []
    for s, i in zip(scores[0], ids[0]):
        if i == -1: continue
        m = all_metadata[i]
        if dept and m["department"].lower() != dept.lower(): continue
        out.append({"text": all_chunks[i], "score": float(s), "meta": m})
        if len(out) >= k: break
    return out

test_queries = [
    "remote work policy senior engineers",
    "Q3 revenue APAC performance",
    "GDPR data retention rules",
]
for q in test_queries:
    res = retrieve(q, k=2)
    print(f"\nQuery: '{q}'")
    for r in res:
        print(f"  [{r['score']:.3f}] {r['meta']['doc_id']} — {r['text'][:80]}...")
print("\n✓ Stage 2 complete")

# ── STAGE 3: GENERATION ───────────────────────────────────────────
print("\n[STAGE 3/5] ANSWER GENERATION (Local, no LLM API)")
print("—"*45)

def extract_answer(query, retrieved):
    q_words = set(re.findall(r'\b\w{4,}\b', query.lower()))
    sents = []
    for r in retrieved:
        for s in re.split(r'[.!?]', r["text"]):
            s = s.strip()
            if len(s) > 20:
                ov = len(q_words & set(re.findall(r'\b\w{4,}\b', s.lower())))
                sents.append((ov + r["score"], s, r["meta"]["doc_id"]))
    sents.sort(reverse=True)
    if not sents:
        return "Insufficient context.", []
    top     = sents[:3]
    answer  = ". ".join([t[1] for t in top]) + "."
    sources = list(set([t[2] for t in top]))
    return answer, sources

gen_queries = [
    "What is the parental leave policy?",
    "How do I submit an expense report?",
    "What are the code review requirements?",
    "Who should I contact for payroll?",
]

generation_log = []
for q in gen_queries:
    res     = retrieve(q, k=4)
    ans, src = extract_answer(q, res)
    print(f"\nQ: {q}")
    print(f"A: {ans[:140]}...")
    print(f"   Sources: {', '.join(src)}")
    generation_log.append({"question": q, "answer": ans, "sources": src})

print("\n✓ Stage 3 complete")

# ── STAGE 4: MULTI-AGENT ──────────────────────────────────────────
print("\n[STAGE 4/5] MULTI-AGENT WORKFLOW (LangGraph-style)")
print("—"*45)

ANALYST_KW    = {"revenue","metric","performance","q3","q4","target","expense","sales"}
RESEARCHER_KW = {"policy","rule","compliance","gdpr","process","how","contact","must"}
WRITER_KW     = {"summary","report","write","brief","explain","roadmap","overview"}

def route(query):
    w = set(re.findall(r'\b\w+\b', query.lower()))
    a = len(w & ANALYST_KW)
    r = len(w & RESEARCHER_KW)
    wr = len(w & WRITER_KW)
    if a >= r and a >= wr:   return "analyst"
    elif r >= wr:             return "researcher"
    else:                     return "writer"

def run_agent_pipeline(query):
    trace  = []
    rte    = route(query)
    trace.append(f"Supervisor → {rte}")
    docs   = retrieve(query, k=4)
    trace.append(f"Retriever  → {len(docs)} chunks")
    ans, src = extract_answer(query, docs)
    draft  = f"REPORT: {ans}"
    trace.append(f"Writer     → {len(draft)} chars drafted")
    # Validator
    ans_w  = set(re.findall(r'\b\w{5,}\b', ans.lower()))
    ctx_w  = set(re.findall(r'\b\w{5,}\b', " ".join([d["text"] for d in docs]).lower()))
    gnd    = round(len(ans_w & ctx_w) / (len(ans_w)+1e-9), 3)
    passed = gnd >= 0.25
    trace.append(f"Validator  → grounding={gnd:.3f} {'PASS' if passed else 'FAIL'}")
    return {"query": query, "route": rte, "answer": ans, "sources": src,
            "grounding": gnd, "passed": passed, "trace": trace}

agent_queries = [
    "What was Q3 revenue by region?",
    "Explain the GDPR retention policy.",
    "Summarize H1 2025 product roadmap.",
]
agent_log = []
for q in agent_queries:
    r = run_agent_pipeline(q)
    agent_log.append(r)
    print(f"\nQuery: {q}")
    for t in r["trace"]: print(f"  {t}")
    print(f"  Answer: {r['answer'][:100]}...")

print("\n✓ Stage 4 complete")

# ── STAGE 5: EVALUATION ───────────────────────────────────────────
print("\n[STAGE 5/5] EVALUATION (RAGAS-style metrics)")
print("—"*45)

EVAL = [
    {"id":"E01","dept":"HR",          "q":"What is the remote work policy?",            "gt":"4 days remote per week with manager approval"},
    {"id":"E02","dept":"HR",          "q":"How many weeks parental leave for primary?",  "gt":"16 weeks fully paid parental leave"},
    {"id":"E03","dept":"Finance",     "q":"What was Q3 APAC revenue growth?",            "gt":"APAC grew 23 percent year over year"},
    {"id":"E04","dept":"Legal",       "q":"What is GDPR default retention period?",      "gt":"3 years post end of customer relationship"},
    {"id":"E05","dept":"HR",          "q":"Who to contact for payroll queries?",         "gt":"payroll@company.com or extension 4400"},
    {"id":"E06","dept":"Finance",     "q":"What is the expense submission deadline?",    "gt":"within 30 days via Concur portal"},
    {"id":"E07","dept":"Engineering", "q":"How many approvals for code review?",         "gt":"at least one peer review before merging"},
    {"id":"E08","dept":"Finance",     "q":"What is the Q4 2024 revenue target?",         "gt":"INR 460 crores"},
    {"id":"E09","dept":"Product",     "q":"What are Q3 monthly active users?",           "gt":"142000 monthly active users"},
    {"id":"E10","dept":"Engineering", "q":"What is P1 incident response time?",          "gt":"15 minutes response 5 minutes acknowledgment"},
]

def cos(a, b): return float(np.dot(a, b)/(np.linalg.norm(a)*np.linalg.norm(b)+1e-9))

eval_results = []
for item in EVAL:
    docs   = retrieve(item["q"], k=5)
    ans, _ = extract_answer(item["q"], docs)
    ctxs   = [d["text"] for d in docs]

    aw     = set(re.findall(r'\b\w{5,}\b', ans.lower()))
    ctxw   = set(re.findall(r'\b\w{5,}\b', " ".join(ctxs).lower()))
    gtw    = set(re.findall(r'\b\w{5,}\b', item["gt"].lower()))

    faith  = round(len(aw & ctxw)/(len(aw)+1e-9), 3)
    qe     = model.encode([item["q"]], normalize_embeddings=True)[0]
    ae     = model.encode([ans],       normalize_embeddings=True)[0]
    relev  = round(cos(qe, ae), 3)
    q_prec = sum(1 for d in docs if cos(qe, model.encode([d["text"]], normalize_embeddings=True)[0]) > 0.30)
    prec   = round(q_prec/len(docs), 3) if docs else 0
    recall = round(len(gtw & ctxw)/(len(gtw)+1e-9), 3)
    overall = round(0.30*faith + 0.30*relev + 0.20*prec + 0.20*recall, 3)

    r = {"id":item["id"],"department":item["dept"],"question":item["q"],
         "generated_answer":ans[:200],"ground_truth":item["gt"],
         "faithfulness":faith,"answer_relevancy":relev,
         "context_precision":prec,"context_recall":recall,
         "overall_score":overall,"pass":overall>=0.50}
    eval_results.append(r)
    status = "✓" if r["pass"] else "✗"
    print(f"  [{status}] {item['id']} | {item['dept']:12} | F={faith:.2f} AR={relev:.2f} CP={prec:.2f} CR={recall:.2f} | {overall:.2f}")

m  = lambda k: round(float(np.mean([r[k] for r in eval_results])), 4)
agg = {k: m(k) for k in ["faithfulness","answer_relevancy","context_precision","context_recall","overall_score"]}
n_pass = sum(1 for r in eval_results if r["pass"])
h_flagged = sum(1 for r in eval_results if r["faithfulness"] < 0.25)

print(f"\n  Faithfulness:       {agg['faithfulness']:.4f}")
print(f"  Answer Relevancy:   {agg['answer_relevancy']:.4f}")
print(f"  Context Precision:  {agg['context_precision']:.4f}")
print(f"  Context Recall:     {agg['context_recall']:.4f}")
print(f"  Overall Score:      {agg['overall_score']:.4f}")
print(f"  Pass Rate:          {n_pass}/{len(eval_results)}")
print(f"  Hallucination Rate: {h_flagged/len(eval_results):.1%}")

from google.colab import userdata
userdata.get('HF_TOKEN')