# -*- coding: utf-8 -*-
"""Wallmart_Adv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12d7vYf6OVWpagJfocm8Vm5EUrW6XxUeh
"""

# 1. Import Libraries
# ==============================
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# 2. Load Data (Colab Friendly)
# ==============================
# Upload file manually OR use path
df = pd.read_csv('/content/Wallmart.csv')

# Basic Info
print(df.shape)
print(df.info())
print(df.head())

# 3. Data Cleaning
# ==============================
# Fix column names (if needed)
df.columns = df.columns.str.strip()

# Convert categorical columns
cat_cols = ['Gender', 'Age', 'City_Category', 'Stay_In_Current_City_Years']
for col in cat_cols:
    df[col] = df[col].astype('category')

# 4. EDA (Basic Analysis)
# ==============================
print("\nGender Distribution:\n", df['Gender'].value_counts(normalize=True)*100)
print("\nAge Distribution:\n", df['Age'].value_counts(normalize=True)*100)

# 5. Visualization (No seaborn issues)
# ==============================

# Gender count
df['Gender'].value_counts().plot(kind='bar')
plt.title("Gender Distribution")
plt.show()

# Purchase distribution
df['Purchase'].plot(kind='hist', bins=30)
plt.title("Purchase Distribution")
plt.show()

# 6. Feature Engineering
# ==============================

# Encode categorical variables
df_encoded = pd.get_dummies(df, columns=['Gender','Age','City_Category','Stay_In_Current_City_Years'], drop_first=True)

# 7. ML MODEL (Regression)
# ==============================

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error, r2_score

# Drop rows with any NaN values from the encoded DataFrame
df_cleaned = df_encoded.dropna()

X = df_cleaned.drop(['Purchase', 'User_ID', 'Product_ID'], axis=1)
y = df_cleaned['Purchase']

# Split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Model
model = RandomForestRegressor(n_estimators=50, random_state=42)
model.fit(X_train, y_train)

# Predictions
y_pred = model.predict(X_test)

# Evaluation
print("\nMAE:", mean_absolute_error(y_test, y_pred))
print("R2 Score:", r2_score(y_test, y_pred))

# 8. Feature Importance
# ==============================
importance = pd.Series(model.feature_importances_, index=X.columns)
importance.sort_values(ascending=False).head(10).plot(kind='barh')
plt.title("Top Features Influencing Purchase")
plt.show()

"""ADVANCED ML PIPELINE"""

# 1. Install XGBoost (Colab only)
# ==============================
!pip install xgboost

#2. Import Libraries
# ==============================
import pandas as pd
import numpy as np
from xgboost import XGBRegressor

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import mean_absolute_error, r2_score

# 3. Load Data
# ==============================
df = pd.read_csv('/content/Wallmart.csv')
df.columns = df.columns.str.strip()

# 4. Feature Engineering
# ==============================
df.fillna(0, inplace=True)

# One-hot encoding
df_encoded = pd.get_dummies(df, columns=[
    'Gender','Age','City_Category','Stay_In_Current_City_Years'
], drop_first=True)

# Define features
X = df_encoded.drop(['Purchase', 'User_ID', 'Product_ID'], axis=1)
y = df_encoded['Purchase']

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 5. BASE XGBOOST MODEL
# ==============================
xgb = XGBRegressor(
    n_estimators=200,
    learning_rate=0.1,
    max_depth=6,
    random_state=42,
    n_jobs=-1
)

xgb.fit(X_train, y_train)

y_pred = xgb.predict(X_test)

print("Base Model MAE:", mean_absolute_error(y_test, y_pred))
print("Base Model R2:", r2_score(y_test, y_pred))

# 6. HYPERPARAMETER TUNING
# ==============================

param_grid = {
    'n_estimators': [100, 200],
    'max_depth': [4, 6, 8],
    'learning_rate': [0.05, 0.1],
    'subsample': [0.8, 1.0]
}

grid = GridSearchCV(
    estimator=XGBRegressor(random_state=42, n_jobs=-1),
    param_grid=param_grid,
    cv=3,
    scoring='r2',
    verbose=1
)

grid.fit(X_train, y_train)

print("Best Parameters:", grid.best_params_)

# 7. FINAL MODEL
# ==============================
best_model = grid.best_estimator_

y_pred_final = best_model.predict(X_test)

print("\nTuned Model MAE:", mean_absolute_error(y_test, y_pred_final))
print("Tuned Model R2:", r2_score(y_test, y_pred_final))

# 8. FEATURE IMPORTANCE
# ==============================
import matplotlib.pyplot as plt

importance = pd.Series(best_model.feature_importances_, index=X.columns)
importance.sort_values(ascending=False).head(10).plot(kind='barh')
plt.title("Top Features Influencing Purchase")
plt.show()